### ISSUE TITLE
Let RelaxNG validation function work again

### ISSUE THREAD

**Issue by naruoga** [naruoga/jOpenDocument#5]
The original project worked its RelaxNG functions fine, but at this time, our project has broken this feature.
The function is quite important for XML handling library, so we have to it could work well again as soon as possible.

**Comment by naruoga** [comment]
In the test `OOXMLTest.testValidation`, it causes the following exception.

```
"C:\Program Files\AdoptOpenJDK\jdk-8.0.292.10-hotspot\bin\java.exe" -ea -Didea.test.cyclic.buffer.size=1048576 "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1.3.1\lib\idea_rt.jar=53169:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1.3.1\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1.3.1\lib\idea_rt.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1.3.1\plugins\junit\lib\junit5-rt.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1.3.1\plugins\junit\lib\junit-rt.jar;C:\Program Files\AdoptOpenJDK\jdk-8.0.292.10-hotspot\jre\lib\charsets.jar;C:\Program Files\AdoptOpenJDK\jdk-8.0.292.10-hotspot\jre\lib\ext\access-bridge-64.jar;C:\Program Files\AdoptOpenJDK\jdk-8.0.292.10-hotspot\jre\lib\ext\cldrdata.jar;C:\Program Files\AdoptOpenJDK\jdk-8.0.292.10-hotspot\jre\lib\ext\dnsns.jar;C:\Program Files\AdoptOpenJDK\jdk-8.0.292.10-hotspot\jre\lib\ext\jaccess.jar;C:\Program Files\AdoptOpenJDK\jdk-8.0.292.10-hotspot\jre\lib\ext\localedata.jar;C:\Program Files\AdoptOpenJDK\jdk-8.0.292.10-hotspot\jre\lib\ext\nashorn.jar;C:\Program Files\AdoptOpenJDK\jdk-8.0.292.10-hotspot\jre\lib\ext\sunec.jar;C:\Program Files\AdoptOpenJDK\jdk-8.0.292.10-hotspot\jre\lib\ext\sunjce_provider.jar;C:\Program Files\AdoptOpenJDK\jdk-8.0.292.10-hotspot\jre\lib\ext\sunmscapi.jar;C:\Program Files\AdoptOpenJDK\jdk-8.0.292.10-hotspot\jre\lib\ext\sunpkcs11.jar;C:\Program Files\AdoptOpenJDK\jdk-8.0.292.10-hotspot\jre\lib\ext\zipfs.jar;C:\Program Files\AdoptOpenJDK\jdk-8.0.292.10-hotspot\jre\lib\jce.jar;C:\Program Files\AdoptOpenJDK\jdk-8.0.292.10-hotspot\jre\lib\jfr.jar;C:\Program Files\AdoptOpenJDK\jdk-8.0.292.10-hotspot\jre\lib\jsse.jar;C:\Program Files\AdoptOpenJDK\jdk-8.0.292.10-hotspot\jre\lib\management-agent.jar;C:\Program Files\AdoptOpenJDK\jdk-8.0.292.10-hotspot\jre\lib\resources.jar;C:\Program Files\AdoptOpenJDK\jdk-8.0.292.10-hotspot\jre\lib\rt.jar;C:\Users\naruhiko\gosrc\src\github.com\naruoga\jOpenDocument\target\test-classes;C:\Users\naruhiko\gosrc\src\github.com\naruoga\jOpenDocument\target\classes;C:\Users\naruhiko\.m2\repository\org\apache\commons\commons-collections4\4.4\commons-collections4-4.4.jar;C:\Users\naruhiko\.m2\repository\org\ow2\asm\asm\9.1\asm-9.1.jar;C:\Users\naruhiko\.m2\repository\org\ow2\asm\asm-analysis\9.1\asm-analysis-9.1.jar;C:\Users\naruhiko\.m2\repository\org\ow2\asm\asm-commons\9.1\asm-commons-9.1.jar;C:\Users\naruhiko\.m2\repository\org\ow2\asm\asm-tree\9.1\asm-tree-9.1.jar;C:\Users\naruhiko\.m2\repository\org\ow2\asm\asm-util\9.1\asm-util-9.1.jar;C:\Users\naruhiko\.m2\repository\org\apache\bcel\bcel\6.5.0\bcel-6.5.0.jar;C:\Users\naruhiko\.m2\repository\org\dom4j\dom4j\2.1.3\dom4j-2.1.3.jar;C:\Users\naruhiko\.m2\repository\org\apache\commons\commons-lang3\3.12.0\commons-lang3-3.12.0.jar;C:\Users\naruhiko\.m2\repository\org\apache\commons\commons-text\1.9\commons-text-1.9.jar;C:\Users\naruhiko\.m2\repository\org\slf4j\slf4j-api\1.8.0-beta4\slf4j-api-1.8.0-beta4.jar;C:\Users\naruhiko\.m2\repository\com\github\spotbugs\spotbugs-annotations\4.2.3\spotbugs-annotations-4.2.3.jar;C:\Users\naruhiko\.m2\repository\com\google\code\findbugs\jsr305\3.0.2\jsr305-3.0.2.jar;C:\Users\naruhiko\.m2\repository\com\google\code\gson\gson\2.8.6\gson-2.8.6.jar;C:\Users\naruhiko\.m2\repository\jaxen\jaxen\1.2.0\jaxen-1.2.0.jar;C:\Users\naruhiko\.m2\repository\net\sf\saxon\Saxon-HE\10.3\Saxon-HE-10.3.jar;C:\Users\naruhiko\.m2\repository\org\jopendocument\isorelax-jaxp-bridge-ILM\1.1\isorelax-jaxp-bridge-ILM-1.1.jar;C:\Users\naruhiko\.m2\repository\msv\msv\20050913\msv-20050913.jar;C:\Users\naruhiko\.m2\repository\msv\relaxngDatatype\20050913\relaxngDatatype-20050913.jar;C:\Users\naruhiko\.m2\repository\msv\xsdlib\20050913\xsdlib-20050913.jar;C:\Users\naruhiko\.m2\repository\msv\isorelax\20050913\isorelax-20050913.jar;C:\Users\naruhiko\.m2\repository\net\jcip\jcip-annotations\1.0\jcip-annotations-1.0.jar;C:\Users\naruhiko\.m2\repository\org\jdom\jdom\1.1.3\jdom-1.1.3.jar;C:\Users\naruhiko\.m2\repository\org\jdom\jdom2\2.0.6\jdom2-2.0.6.jar;C:\Users\naruhiko\.m2\repository\org\mozilla\rhino\1.7.13\rhino-1.7.13.jar;C:\Users\naruhiko\.m2\repository\ognl\ognl\3.2.20\ognl-3.2.20.jar;C:\Users\naruhiko\.m2\repository\org\javassist\javassist\3.24.1-GA\javassist-3.24.1-GA.jar;C:\Users\naruhiko\.m2\repository\org\jopendocument\ognl-engine\2.6.9\ognl-engine-2.6.9.jar;C:\Users\naruhiko\.m2\repository\com\itextpdf\itextpdf\5.5.13.2\itextpdf-5.5.13.2.jar;C:\Users\naruhiko\.m2\repository\junit\junit\4.13.2\junit-4.13.2.jar;C:\Users\naruhiko\.m2\repository\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar;C:\Users\naruhiko\.m2\repository\org\apache\maven\plugins\maven-resources-plugin\3.2.0\maven-resources-plugin-3.2.0.jar;C:\Users\naruhiko\.m2\repository\org\apache\maven\maven-plugin-api\3.1.0\maven-plugin-api-3.1.0.jar;C:\Users\naruhiko\.m2\repository\org\apache\maven\maven-artifact\3.1.0\maven-artifact-3.1.0.jar;C:\Users\naruhiko\.m2\repository\org\apache\maven\maven-core\3.1.0\maven-core-3.1.0.jar;C:\Users\naruhiko\.m2\repository\org\apache\maven\maven-settings\3.1.0\maven-settings-3.1.0.jar;C:\Users\naruhiko\.m2\repository\org\apache\maven\maven-settings-builder\3.1.0\maven-settings-builder-3.1.0.jar;C:\Users\naruhiko\.m2\repository\org\apache\maven\maven-repository-metadata\3.1.0\maven-repository-metadata-3.1.0.jar;C:\Users\naruhiko\.m2\repository\org\apache\maven\maven-model-builder\3.1.0\maven-model-builder-3.1.0.jar;C:\Users\naruhiko\.m2\repository\org\apache\maven\maven-aether-provider\3.1.0\maven-aether-provider-3.1.0.jar;C:\Users\naruhiko\.m2\repository\org\eclipse\aether\aether-spi\0.9.0.M2\aether-spi-0.9.0.M2.jar;C:\Users\naruhiko\.m2\repository\org\eclipse\aether\aether-impl\0.9.0.M2\aether-impl-0.9.0.M2.jar;C:\Users\naruhiko\.m2\repository\org\eclipse\aether\aether-api\0.9.0.M2\aether-api-0.9.0.M2.jar;C:\Users\naruhiko\.m2\repository\org\eclipse\aether\aether-util\0.9.0.M2\aether-util-0.9.0.M2.jar;C:\Users\naruhiko\.m2\repository\org\codehaus\plexus\plexus-classworlds\2.4.2\plexus-classworlds-2.4.2.jar;C:\Users\naruhiko\.m2\repository\org\sonatype\plexus\plexus-sec-dispatcher\1.3\plexus-sec-dispatcher-1.3.jar;C:\Users\naruhiko\.m2\repository\org\sonatype\plexus\plexus-cipher\1.4\plexus-cipher-1.4.jar;C:\Users\naruhiko\.m2\repository\org\apache\maven\maven-model\3.1.0\maven-model-3.1.0.jar;C:\Users\naruhiko\.m2\repository\org\codehaus\plexus\plexus-component-annotations\2.0.0\plexus-component-annotations-2.0.0.jar;C:\Users\naruhiko\.m2\repository\org\codehaus\plexus\plexus-interpolation\1.26\plexus-interpolation-1.26.jar;C:\Users\naruhiko\.m2\repository\org\eclipse\sisu\org.eclipse.sisu.plexus\0.0.0.M2a\org.eclipse.sisu.plexus-0.0.0.M2a.jar;C:\Users\naruhiko\.m2\repository\javax\enterprise\cdi-api\1.0\cdi-api-1.0.jar;C:\Users\naruhiko\.m2\repository\javax\annotation\jsr250-api\1.0\jsr250-api-1.0.jar;C:\Users\naruhiko\.m2\repository\javax\inject\javax.inject\1\javax.inject-1.jar;C:\Users\naruhiko\.m2\repository\com\google\guava\guava\10.0.1\guava-10.0.1.jar;C:\Users\naruhiko\.m2\repository\org\sonatype\sisu\sisu-guice\3.1.0\sisu-guice-3.1.0-no_aop.jar;C:\Users\naruhiko\.m2\repository\aopalliance\aopalliance\1.0\aopalliance-1.0.jar;C:\Users\naruhiko\.m2\repository\org\eclipse\sisu\org.eclipse.sisu.inject\0.0.0.M2a\org.eclipse.sisu.inject-0.0.0.M2a.jar;C:\Users\naruhiko\.m2\repository\asm\asm\3.3.1\asm-3.3.1.jar;C:\Users\naruhiko\.m2\repository\org\apache\maven\shared\maven-filtering\3.2.0\maven-filtering-3.2.0.jar;C:\Users\naruhiko\.m2\repository\org\apache\maven\shared\maven-shared-utils\3.3.3\maven-shared-utils-3.3.3.jar;C:\Users\naruhiko\.m2\repository\org\sonatype\plexus\plexus-build-api\0.0.7\plexus-build-api-0.0.7.jar;C:\Users\naruhiko\.m2\repository\commons-io\commons-io\2.6\commons-io-2.6.jar;C:\Users\naruhiko\.m2\repository\org\apache\maven\plugins\maven-source-plugin\3.2.1\maven-source-plugin-3.2.1.jar;C:\Users\naruhiko\.m2\repository\org\apache\maven\maven-archiver\3.5.0\maven-archiver-3.5.0.jar;C:\Users\naruhiko\.m2\repository\org\codehaus\plexus\plexus-archiver\4.2.1\plexus-archiver-4.2.1.jar;C:\Users\naruhiko\.m2\repository\org\codehaus\plexus\plexus-io\3.2.0\plexus-io-3.2.0.jar;C:\Users\naruhiko\.m2\repository\org\apache\commons\commons-compress\1.19\commons-compress-1.19.jar;C:\Users\naruhiko\.m2\repository\org\iq80\snappy\snappy\0.4\snappy-0.4.jar;C:\Users\naruhiko\.m2\repository\org\tukaani\xz\1.8\xz-1.8.jar;C:\Users\naruhiko\.m2\repository\org\codehaus\plexus\plexus-utils\3.3.0\plexus-utils-3.3.0.jar" com.intellij.rt.junit.JUnitStarter -ideVersion5 @w@C:\Users\naruhiko\AppData\Local\Temp\idea_working_dirs_junit.tmp @C:\Users\naruhiko\AppData\Local\Temp\idea_junit.tmp -socket53168

java.lang.IllegalStateException: relaxNG schemas pb

	at org.jopendocument.dom.OOXML$XML_OD.getValidator(OOXML.java:686)
	at org.jopendocument.dom.ODPackage.validateSubDocuments(ODPackage.java:607)
	at org.jopendocument.dom.OOXMLTest.testValidation(OOXMLTest.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:177)
	at junit.framework.TestCase.runBare(TestCase.java:142)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:221)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: org.xml.sax.SAXParseException; systemId: file:/C:/Users/naruhiko/gosrc/src/github.com/naruoga/jOpenDocument/target/classes/oofficeDTDs/OpenDocument-schema-v1.1.rng; lineNumber: 123; columnNumber: 36; 同名のパターンが既に定義されています。combine属性を使って結合するか、パターン名を"office-meta-content"以外のものに変更してください
	at com.sun.msv.verifier.jarv.FactoryImpl$ThrowController.error(FactoryImpl.java:145)
	at com.sun.msv.reader.Controller.error(Controller.java:49)
	at com.sun.msv.reader.GrammarReader.reportError(GrammarReader.java:746)
	at com.sun.msv.reader.GrammarReader.reportError(GrammarReader.java:704)
	at com.sun.msv.reader.trex.ng.DefineState.doCombine(DefineState.java:77)
	at com.sun.msv.reader.trex.DefineState.endSelf(DefineState.java:80)
	at com.sun.msv.reader.trex.ng.DefineState.endSelf(DefineState.java:57)
	at com.sun.msv.reader.SimpleState.endElement(SimpleState.java:101)
	at org.xml.sax.helpers.XMLFilterImpl.endElement(XMLFilterImpl.java:570)
	at com.sun.msv.reader.trex.TREXBaseReader.endElement(TREXBaseReader.java:184)
	at com.sun.msv.reader.trex.ng.RELAXNGReader.endElement(RELAXNGReader.java:527)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2967)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.msv.reader.GrammarReader._parse(GrammarReader.java:456)
	at com.sun.msv.reader.GrammarReader.switchSource(GrammarReader.java:429)
	at com.sun.msv.reader.GrammarReader.switchSource(GrammarReader.java:402)
	at com.sun.msv.reader.trex.IncludeMergeState.endSelf(IncludeMergeState.java:43)
	at com.sun.msv.reader.trex.ng.IncludeMergeState.endSelf(IncludeMergeState.java:67)
	at com.sun.msv.reader.SimpleState.endElement(SimpleState.java:101)
	at org.xml.sax.helpers.XMLFilterImpl.endElement(XMLFilterImpl.java:570)
	at com.sun.msv.reader.trex.TREXBaseReader.endElement(TREXBaseReader.java:184)
	at com.sun.msv.reader.trex.ng.RELAXNGReader.endElement(RELAXNGReader.java:527)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2967)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.msv.reader.GrammarReader._parse(GrammarReader.java:456)
	at com.sun.msv.reader.GrammarReader.parse(GrammarReader.java:444)
	at com.sun.msv.verifier.jarv.RELAXNGFactoryImpl.parse(RELAXNGFactoryImpl.java:39)
	at com.sun.msv.verifier.jarv.FactoryImpl.compileSchema(FactoryImpl.java:98)
	at org.iso_relax.verifier.jaxp.validation.SchemaFactoryImpl.compileSchema(SchemaFactoryImpl.java:87)
	at org.iso_relax.verifier.jaxp.validation.SchemaFactoryImpl.newSchema(SchemaFactoryImpl.java:62)
	at javax.xml.validation.SchemaFactory.newSchema(SchemaFactory.java:638)
	at javax.xml.validation.SchemaFactory.newSchema(SchemaFactory.java:670)
	at org.jopendocument.dom.OOXML$XML_OD.createSchema(OOXML.java:660)
	at org.jopendocument.dom.OOXML$XML_OD.getSchema(OOXML.java:665)
	at org.jopendocument.dom.OOXML$XML_OD.getValidator(OOXML.java:684)
	... 29 more

7 23, 2021 5:24:16 午後 org.jopendocument.dom.style.data.DataStyle reportError
警告: Boolean not localized
7 23, 2021 5:24:16 午後 org.jopendocument.dom.style.data.DataStyle reportError
警告: Boolean not localized
7 23, 2021 5:24:16 午後 org.jopendocument.dom.style.data.DataStyle reportError
警告: Boolean not localized

java.lang.IllegalStateException: relaxNG schemas pb

	at org.jopendocument.dom.OOXML$XML_OD.getValidator(OOXML.java:686)
	at org.jopendocument.dom.OOXML.getValidator(OOXML.java:214)
	at org.jopendocument.dom.ODXMLDocument.getValidator(ODXMLDocument.java:139)
	at org.jopendocument.dom.spreadsheet.SheetTest.testCreate(SheetTest.java:114)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:177)
	at junit.framework.TestCase.runBare(TestCase.java:142)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:221)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: org.xml.sax.SAXParseException; systemId: file:/C:/Users/naruhiko/gosrc/src/github.com/naruoga/jOpenDocument/target/classes/oofficeDTDs/OpenDocument-schema-v1.1.rng; lineNumber: 123; columnNumber: 36; 同名のパターンが既に定義されています。combine属性を使って結合するか、パターン名を"office-meta-content"以外のものに変更してください
	at com.sun.msv.verifier.jarv.FactoryImpl$ThrowController.error(FactoryImpl.java:145)
	at com.sun.msv.reader.Controller.error(Controller.java:49)
	at com.sun.msv.reader.GrammarReader.reportError(GrammarReader.java:746)
	at com.sun.msv.reader.GrammarReader.reportError(GrammarReader.java:704)
	at com.sun.msv.reader.trex.ng.DefineState.doCombine(DefineState.java:77)
	at com.sun.msv.reader.trex.DefineState.endSelf(DefineState.java:80)
	at com.sun.msv.reader.trex.ng.DefineState.endSelf(DefineState.java:57)
	at com.sun.msv.reader.SimpleState.endElement(SimpleState.java:101)
	at org.xml.sax.helpers.XMLFilterImpl.endElement(XMLFilterImpl.java:570)
	at com.sun.msv.reader.trex.TREXBaseReader.endElement(TREXBaseReader.java:184)
	at com.sun.msv.reader.trex.ng.RELAXNGReader.endElement(RELAXNGReader.java:527)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2967)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.msv.reader.GrammarReader._parse(GrammarReader.java:456)
	at com.sun.msv.reader.GrammarReader.switchSource(GrammarReader.java:429)
	at com.sun.msv.reader.GrammarReader.switchSource(GrammarReader.java:402)
	at com.sun.msv.reader.trex.IncludeMergeState.endSelf(IncludeMergeState.java:43)
	at com.sun.msv.reader.trex.ng.IncludeMergeState.endSelf(IncludeMergeState.java:67)
	at com.sun.msv.reader.SimpleState.endElement(SimpleState.java:101)
	at org.xml.sax.helpers.XMLFilterImpl.endElement(XMLFilterImpl.java:570)
	at com.sun.msv.reader.trex.TREXBaseReader.endElement(TREXBaseReader.java:184)
	at com.sun.msv.reader.trex.ng.RELAXNGReader.endElement(RELAXNGReader.java:527)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2967)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.msv.reader.GrammarReader._parse(GrammarReader.java:456)
	at com.sun.msv.reader.GrammarReader.parse(GrammarReader.java:444)
	at com.sun.msv.verifier.jarv.RELAXNGFactoryImpl.parse(RELAXNGFactoryImpl.java:39)
	at com.sun.msv.verifier.jarv.FactoryImpl.compileSchema(FactoryImpl.java:98)
	at org.iso_relax.verifier.jaxp.validation.SchemaFactoryImpl.compileSchema(SchemaFactoryImpl.java:87)
	at org.iso_relax.verifier.jaxp.validation.SchemaFactoryImpl.newSchema(SchemaFactoryImpl.java:62)
	at javax.xml.validation.SchemaFactory.newSchema(SchemaFactory.java:638)
	at javax.xml.validation.SchemaFactory.newSchema(SchemaFactory.java:670)
	at org.jopendocument.dom.OOXML$XML_OD.createSchema(OOXML.java:660)
	at org.jopendocument.dom.OOXML$XML_OD.getSchema(OOXML.java:665)
	at org.jopendocument.dom.OOXML$XML_OD.getValidator(OOXML.java:684)
	... 30 more
```

I'm running this test in Japanese locale and an exception is in Japanese;
```
Caused by: org.xml.sax.SAXParseException; systemId: file:/C:/Users/naruhiko/gosrc/src/github.com/naruoga/jOpenDocument/target/classes/oofficeDTDs/OpenDocument-schema-v1.1.rng; lineNumber: 123; columnNumber: 36; 同名のパターンが既に定義されています。combine属性を使って結合するか、パターン名を"office-meta-content"以外のものに変更してください
```
It means "The different patterns which have same name has already defined,  Combine them with combine attribute, or change the pattern name to other than "office-meta-content".
